### ISSUE TITLE
这个描述对吗？

### ISSUE THREAD

**Issue by cute-angelia** [deatil/go-event#2]
`github.com/deatil/go-event` 库中的 `Listen` 和 `Subscribe` 方法是用来实现观察者模式的两个不同的方法。它们的主要区别如下:

1. **Listen**:
   - `Listen` 方法用于注册一个事件监听器,当指定事件被触发时,该监听器会被调用。
   - 使用 `Listen` 方法注册的监听器,会一直存在于事件系统中,直到手动移除或程序结束。
   - 该方法通常用于注册全局性的、长期运行的事件监听器。

2. **Subscribe**:
   - `Subscribe` 方法用于订阅一个事件,它返回一个取消订阅的函数。
   - 使用 `Subscribe` 方法订阅的监听器,只会在当前事件被触发时被调用一次,然后自动取消订阅。
   - 该方法通常用于注册一次性的、短期的事件监听器。

总的来说,`Listen` 方法更适合于注册长期运行的事件监听器,而 `Subscribe` 方法更适合于注册一次性的事件监听器。

具体使用时,根据您的需求来选择合适的方法:

- 如果您需要一个长期运行的事件监听器,可以使用 `Listen` 方法。
- 如果您只需要一次性地响应某个事件,可以使用 `Subscribe` 方法。

**Comment by deatil** [comment]
Subscribe 不对。
Subscribe是订阅，比listen的用法多
go-event没有实现只执行一次事件，都是一直存在的
go-event 是类似 laravel 的事件，只有触发时才执行

**Comment by cute-angelia** [comment]
谢谢。
